version: '3.5'
networks:
      postgres_network: 
services:
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
#      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:5432
    networks:
      - postgres_network
    volumes:
      - postgres-volume:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${ADMIN_HOST}
    restart: always
    ports:
      - ${ADMIN_PORT}:80
    networks:
      - postgres_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=${ADMIN_DFT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${ADMIN_DFT_PASS}

volumes:
  postgres-volume:

